name: GitHub Profile Views Counter CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours.

jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Github Profile Views Counter
        uses: gayanvoice/github-profile-views-counter-action@3.0.0
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
